### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ghost** [DrewDahlman/headless-wordpress#3]
Hi, this is a brand new solution to me and seems to be a great way to let content creators keep using the Wordpress' awesome platform without all the bloater that developers faces to build the website front-end.

But what about the downsides? Can you share a little about the experiencie of running real websites using this solution?

**Comment by DrewDahlman** [comment]
Wow somehow I missed this - sorry for the delay!

In terms of downsides I would say having to rely on the minimal plugin setup is about it which really isn't an issue as this method of using plugins is minimal and allows you to craft the content format exactly to your own spec... technically this can be more secure, faster and take away all of the headaches commonly associated with Wordpress.

For publishing content for sites - this really is as straight forward as it seems. All you are doing it publishing JSON and creating a better way to manage the content. This setup in here will allow you to export the database and actually just share the project locally and never publish to a server - just keeping everything on s3.
